with-expecter: true
disable-version-string: true
inpackage: false
dir: "internal/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.MockName}}_mock.go"
packages:
  inbox451/internal/storage:
    config:
      all: true
