coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true # Don't fail CI checks
    patch:
      default:
        target: auto
        threshold: 10%
        informational: true # Don't fail CI checks

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "internal/mocks/**/*" # Mocks
  - "**/*.pb.go" # Generated protobuf files
