services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mercury
      POSTGRES_PASSWORD: mercury
      POSTGRES_DB: mercury
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
