services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mercury
      POSTGRES_PASSWORD: mercury
      POSTGRES_DB: mercury
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mercury"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
