server:
  http:
    port: ":8080"
  smtp:
    port: ":1025"
    domain: "localhost"
    username: ""
    password: ""
  imap:
    port: ":1143"
    hostname: "localhost"
database:
  driver: "sqlite3"
  url: "./database.sqlite3"
logging:
  level: "info"
  format: "json"
