server:
  http:
    port: ":8080"
  smtp:
    host: "localhost"
    domain: "smtp.example.com"
    mta:
      port: "1025"
      tls: false
    msa:
      tls: false
      port: "587"
  imap:
    port: ":1143"
    hostname: "localhost"
  email_domain: "example.com"
database:
  url: "postgres://mercury:mercury@localhost:5432/mercury?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
logging:
  level: "info"
  format: "json"
oidc:
  enabled: false # Set to true to enable OIDC login
  provider_url: "" # e.g., https://accounts.google.com or https://login.microsoftonline.com/{tenantid}/v2.0
  client_id: ""
  client_secret: ""
  # redirect_url is automatically constructed based on app.root_url + /auth/oidc/callback
